// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.5
// source: aadhaarmasker.proto

package aadhaarmaskerpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AadhaarMaskerClient is the client API for AadhaarMasker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AadhaarMaskerClient interface {
	Mask(ctx context.Context, in *AadhaarMaskingRequest, opts ...grpc.CallOption) (*AadhaarMaskingResponse, error)
}

type aadhaarMaskerClient struct {
	cc grpc.ClientConnInterface
}

func NewAadhaarMaskerClient(cc grpc.ClientConnInterface) AadhaarMaskerClient {
	return &aadhaarMaskerClient{cc}
}

func (c *aadhaarMaskerClient) Mask(ctx context.Context, in *AadhaarMaskingRequest, opts ...grpc.CallOption) (*AadhaarMaskingResponse, error) {
	out := new(AadhaarMaskingResponse)
	err := c.cc.Invoke(ctx, "/AadhaarMasker/mask", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AadhaarMaskerServer is the server API for AadhaarMasker service.
// All implementations must embed UnimplementedAadhaarMaskerServer
// for forward compatibility
type AadhaarMaskerServer interface {
	Mask(context.Context, *AadhaarMaskingRequest) (*AadhaarMaskingResponse, error)
	mustEmbedUnimplementedAadhaarMaskerServer()
}

// UnimplementedAadhaarMaskerServer must be embedded to have forward compatible implementations.
type UnimplementedAadhaarMaskerServer struct {
}

func (UnimplementedAadhaarMaskerServer) Mask(context.Context, *AadhaarMaskingRequest) (*AadhaarMaskingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mask not implemented")
}
func (UnimplementedAadhaarMaskerServer) mustEmbedUnimplementedAadhaarMaskerServer() {}

// UnsafeAadhaarMaskerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AadhaarMaskerServer will
// result in compilation errors.
type UnsafeAadhaarMaskerServer interface {
	mustEmbedUnimplementedAadhaarMaskerServer()
}

func RegisterAadhaarMaskerServer(s grpc.ServiceRegistrar, srv AadhaarMaskerServer) {
	s.RegisterService(&AadhaarMasker_ServiceDesc, srv)
}

func _AadhaarMasker_Mask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AadhaarMaskingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AadhaarMaskerServer).Mask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/AadhaarMasker/mask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AadhaarMaskerServer).Mask(ctx, req.(*AadhaarMaskingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AadhaarMasker_ServiceDesc is the grpc.ServiceDesc for AadhaarMasker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AadhaarMasker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "AadhaarMasker",
	HandlerType: (*AadhaarMaskerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "mask",
			Handler:    _AadhaarMasker_Mask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "aadhaarmasker.proto",
}
