// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: aadhaarmasker.proto

package aadhaarmaskerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AadhaarMaskingRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *AadhaarMaskingRequest) Reset() {
	*x = AadhaarMaskingRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aadhaarmasker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AadhaarMaskingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadhaarMaskingRequest) ProtoMessage() {}

func (x *AadhaarMaskingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aadhaarmasker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadhaarMaskingRequest.ProtoReflect.Descriptor instead.
func (*AadhaarMaskingRequest) Descriptor() ([]byte, []int) {
	return file_aadhaarmasker_proto_rawDescGZIP(), []int{0}
}

func (x *AadhaarMaskingRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type AadhaarMaskingResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status   int32  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Suffix   string `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	Document []byte `protobuf:"bytes,3,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *AadhaarMaskingResponse) Reset() {
	*x = AadhaarMaskingResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aadhaarmasker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AadhaarMaskingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AadhaarMaskingResponse) ProtoMessage() {}

func (x *AadhaarMaskingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aadhaarmasker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AadhaarMaskingResponse.ProtoReflect.Descriptor instead.
func (*AadhaarMaskingResponse) Descriptor() ([]byte, []int) {
	return file_aadhaarmasker_proto_rawDescGZIP(), []int{1}
}

func (x *AadhaarMaskingResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AadhaarMaskingResponse) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

func (x *AadhaarMaskingResponse) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

var File_aadhaarmasker_proto protoreflect.FileDescriptor

var file_aadhaarmasker_proto_rawDesc = []byte{
	0x0a, 0x13, 0x61, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x33, 0x0a, 0x15, 0x41, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72,
	0x4d, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x64, 0x0a, 0x16, 0x41, 0x61,
	0x64, 0x68, 0x61, 0x61, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x75,
	0x66, 0x66, 0x69, 0x78, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74,
	0x32, 0x4a, 0x0a, 0x0d, 0x41, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x65,
	0x72, 0x12, 0x39, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x12, 0x16, 0x2e, 0x41, 0x61, 0x64, 0x68,
	0x61, 0x61, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x41, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x69,
	0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x61, 0x0a, 0x1d,
	0x69, 0x6f, 0x2e, 0x73, 0x70, 0x6f, 0x6f, 0x72, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x61, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x42, 0x12, 0x41,
	0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x4d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x73, 0x70, 0x6f, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f,
	0x61, 0x61, 0x64, 0x68, 0x61, 0x61, 0x72, 0x6d, 0x61, 0x73, 0x6b, 0x65, 0x72, 0x70, 0x62, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aadhaarmasker_proto_rawDescOnce sync.Once
	file_aadhaarmasker_proto_rawDescData = file_aadhaarmasker_proto_rawDesc
)

func file_aadhaarmasker_proto_rawDescGZIP() []byte {
	file_aadhaarmasker_proto_rawDescOnce.Do(func() {
		file_aadhaarmasker_proto_rawDescData = protoimpl.X.CompressGZIP(file_aadhaarmasker_proto_rawDescData)
	})
	return file_aadhaarmasker_proto_rawDescData
}

var file_aadhaarmasker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aadhaarmasker_proto_goTypes = []interface{}{
	(*AadhaarMaskingRequest)(nil),  // 0: AadhaarMaskingRequest
	(*AadhaarMaskingResponse)(nil), // 1: AadhaarMaskingResponse
}
var file_aadhaarmasker_proto_depIdxs = []int32{
	0, // 0: AadhaarMasker.mask:input_type -> AadhaarMaskingRequest
	1, // 1: AadhaarMasker.mask:output_type -> AadhaarMaskingResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_aadhaarmasker_proto_init() }
func file_aadhaarmasker_proto_init() {
	if File_aadhaarmasker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_aadhaarmasker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AadhaarMaskingRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aadhaarmasker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AadhaarMaskingResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aadhaarmasker_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_aadhaarmasker_proto_goTypes,
		DependencyIndexes: file_aadhaarmasker_proto_depIdxs,
		MessageInfos:      file_aadhaarmasker_proto_msgTypes,
	}.Build()
	File_aadhaarmasker_proto = out.File
	file_aadhaarmasker_proto_rawDesc = nil
	file_aadhaarmasker_proto_goTypes = nil
	file_aadhaarmasker_proto_depIdxs = nil
}
