// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: dataextractor.proto

package dataextractorpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtractTextRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *ExtractTextRequest) Reset() {
	*x = ExtractTextRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextRequest) ProtoMessage() {}

func (x *ExtractTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextRequest.ProtoReflect.Descriptor instead.
func (*ExtractTextRequest) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{0}
}

func (x *ExtractTextRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type ExtractTextResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
}

func (x *ExtractTextResponse) Reset() {
	*x = ExtractTextResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractTextResponse) ProtoMessage() {}

func (x *ExtractTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractTextResponse.ProtoReflect.Descriptor instead.
func (*ExtractTextResponse) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{1}
}

func (x *ExtractTextResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type ExtractDigitsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document []byte `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
}

func (x *ExtractDigitsRequest) Reset() {
	*x = ExtractDigitsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractDigitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractDigitsRequest) ProtoMessage() {}

func (x *ExtractDigitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractDigitsRequest.ProtoReflect.Descriptor instead.
func (*ExtractDigitsRequest) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{2}
}

func (x *ExtractDigitsRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

type ExtractDigitsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Digits string `protobuf:"bytes,1,opt,name=digits,proto3" json:"digits,omitempty"`
}

func (x *ExtractDigitsResponse) Reset() {
	*x = ExtractDigitsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractDigitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractDigitsResponse) ProtoMessage() {}

func (x *ExtractDigitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractDigitsResponse.ProtoReflect.Descriptor instead.
func (*ExtractDigitsResponse) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{3}
}

func (x *ExtractDigitsResponse) GetDigits() string {
	if x != nil {
		return x.Digits
	}
	return ""
}

type ExtractLabeledValuesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Document []byte   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Labels   []string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty"`
}

func (x *ExtractLabeledValuesRequest) Reset() {
	*x = ExtractLabeledValuesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractLabeledValuesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLabeledValuesRequest) ProtoMessage() {}

func (x *ExtractLabeledValuesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLabeledValuesRequest.ProtoReflect.Descriptor instead.
func (*ExtractLabeledValuesRequest) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{4}
}

func (x *ExtractLabeledValuesRequest) GetDocument() []byte {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *ExtractLabeledValuesRequest) GetLabels() []string {
	if x != nil {
		return x.Labels
	}
	return nil
}

type ExtractLabeledValuesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LabeledValues []*LabeledValue `protobuf:"bytes,1,rep,name=labeled_values,json=labeledValues,proto3" json:"labeled_values,omitempty"`
}

func (x *ExtractLabeledValuesResponse) Reset() {
	*x = ExtractLabeledValuesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExtractLabeledValuesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtractLabeledValuesResponse) ProtoMessage() {}

func (x *ExtractLabeledValuesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtractLabeledValuesResponse.ProtoReflect.Descriptor instead.
func (*ExtractLabeledValuesResponse) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{5}
}

func (x *ExtractLabeledValuesResponse) GetLabeledValues() []*LabeledValue {
	if x != nil {
		return x.LabeledValues
	}
	return nil
}

type LabeledValue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Label string `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *LabeledValue) Reset() {
	*x = LabeledValue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dataextractor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabeledValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabeledValue) ProtoMessage() {}

func (x *LabeledValue) ProtoReflect() protoreflect.Message {
	mi := &file_dataextractor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabeledValue.ProtoReflect.Descriptor instead.
func (*LabeledValue) Descriptor() ([]byte, []int) {
	return file_dataextractor_proto_rawDescGZIP(), []int{6}
}

func (x *LabeledValue) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *LabeledValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_dataextractor_proto protoreflect.FileDescriptor

var file_dataextractor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x64, 0x61, 0x74, 0x61, 0x65, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x12, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74,
	0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64,
	0x6f, 0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x29, 0x0a, 0x13, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x65, 0x78, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65,
	0x78, 0x74, 0x22, 0x32, 0x0a, 0x14, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x69, 0x67,
	0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f,
	0x63, 0x75, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x2f, 0x0a, 0x15, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x64, 0x69, 0x67, 0x69, 0x74, 0x73, 0x22, 0x51, 0x0a, 0x1b, 0x45, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x64, 0x6f, 0x63, 0x75, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x22, 0x54, 0x0a, 0x1c, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x34, 0x0a, 0x0e, 0x6c, 0x61,
	0x62, 0x65, 0x6c, 0x65, 0x64, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x0d, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73,
	0x22, 0x3a, 0x0a, 0x0c, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xe4, 0x01, 0x0a,
	0x0d, 0x44, 0x61, 0x74, 0x61, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x3a,
	0x0a, 0x0b, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x78, 0x74, 0x12, 0x13, 0x2e,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x78, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x14, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x54, 0x65, 0x78, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x0d, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x73, 0x12, 0x15, 0x2e, 0x45, 0x78,
	0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x69, 0x67, 0x69, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x44, 0x69, 0x67, 0x69,
	0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55, 0x0a, 0x14,
	0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4c, 0x61,
	0x62, 0x65, 0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63, 0x74, 0x4c, 0x61, 0x62, 0x65,
	0x6c, 0x65, 0x64, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x61, 0x0a, 0x1d, 0x69, 0x6f, 0x2e, 0x73, 0x70, 0x6f, 0x6f, 0x72, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x64, 0x61, 0x74, 0x61, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x42, 0x12, 0x44, 0x61, 0x74, 0x61, 0x45, 0x78, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x6f, 0x72, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x70, 0x6f, 0x6f, 0x72, 0x73, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x65, 0x78, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x6f, 0x72, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dataextractor_proto_rawDescOnce sync.Once
	file_dataextractor_proto_rawDescData = file_dataextractor_proto_rawDesc
)

func file_dataextractor_proto_rawDescGZIP() []byte {
	file_dataextractor_proto_rawDescOnce.Do(func() {
		file_dataextractor_proto_rawDescData = protoimpl.X.CompressGZIP(file_dataextractor_proto_rawDescData)
	})
	return file_dataextractor_proto_rawDescData
}

var file_dataextractor_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_dataextractor_proto_goTypes = []interface{}{
	(*ExtractTextRequest)(nil),           // 0: ExtractTextRequest
	(*ExtractTextResponse)(nil),          // 1: ExtractTextResponse
	(*ExtractDigitsRequest)(nil),         // 2: ExtractDigitsRequest
	(*ExtractDigitsResponse)(nil),        // 3: ExtractDigitsResponse
	(*ExtractLabeledValuesRequest)(nil),  // 4: ExtractLabeledValuesRequest
	(*ExtractLabeledValuesResponse)(nil), // 5: ExtractLabeledValuesResponse
	(*LabeledValue)(nil),                 // 6: LabeledValue
}
var file_dataextractor_proto_depIdxs = []int32{
	6, // 0: ExtractLabeledValuesResponse.labeled_values:type_name -> LabeledValue
	0, // 1: DataExtractor.ExtractText:input_type -> ExtractTextRequest
	2, // 2: DataExtractor.ExtractDigits:input_type -> ExtractDigitsRequest
	4, // 3: DataExtractor.ExtractLabeledValues:input_type -> ExtractLabeledValuesRequest
	1, // 4: DataExtractor.ExtractText:output_type -> ExtractTextResponse
	3, // 5: DataExtractor.ExtractDigits:output_type -> ExtractDigitsResponse
	5, // 6: DataExtractor.ExtractLabeledValues:output_type -> ExtractLabeledValuesResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_dataextractor_proto_init() }
func file_dataextractor_proto_init() {
	if File_dataextractor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dataextractor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTextRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractTextResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractDigitsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractDigitsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractLabeledValuesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExtractLabeledValuesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dataextractor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabeledValue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dataextractor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dataextractor_proto_goTypes,
		DependencyIndexes: file_dataextractor_proto_depIdxs,
		MessageInfos:      file_dataextractor_proto_msgTypes,
	}.Build()
	File_dataextractor_proto = out.File
	file_dataextractor_proto_rawDesc = nil
	file_dataextractor_proto_goTypes = nil
	file_dataextractor_proto_depIdxs = nil
}
